[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "autocode"
version = "0.1.0"
description = "A library for auto-generating and managing code"
readme = "README.md"
requires-python = ">=3.6"
dependencies = [
    "autochat",
]

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
autocode = "autocode.cli:main"